### ISSUE TITLE
Dynamic bundles and Inline Scripts in ScriptBundle

### ISSUE THREAD

**Issue by yuxhuang** [andrewdavey/cassette#133]
Hi Andrew,

Thanks very much for your great work!

I have a couple questions regarding the bundling mechanism.

First, currently the bundling mechanism requires bundle configurations in the CassetteConfigruation class. The Configure method was executed once when the application starts up. Is there a way to create bundles dynamically and add arbitrary assets into the bundle? So if a page only requires certain assets, these assets can be bundled together without prior configuration.

Second, inline scripts are currently treated as separate bundles and they are always visible on the page. Can they be bundled into a regular bundle? So in production mode, these inline scripts can also be bundled together into the combined and minified script.

Felix

**Comment by andrewdavey** [comment]
Hi Felix, thanks for the questions.

Cassette doesn't currently have a way to dynamically create bundles within a page request. I would be interested to hear more about your use case though. I've found that it's simpler to have a few shared bundles for all pages and then specific per-page bundles as well. Perhaps you have some other approach in mind?

Inline scripts specified in-page can't be combined with the predefined scripts, since those are already minified and cached. Potentially the inline script's content change on each request. This would break all the caching put in place for the predefined bundles.

However, it could be possible to create the inline script during the configuration stage. I don't think the API currently exposes a neat way to do this, but it's possible given Cassette's `IAsset` interface. We can look into this more if it's something you need.
