### ISSUE TITLE
css url expand using _ for . in debug mode

### ISSUE THREAD

**Issue by cliechty** [andrewdavey/cassette#183]
Version 1.1.0-beta2

I found that running our site with debug enabled images defined in css using url are not loading with a 404 error.
If I turn off debug then the images load properly. The difference I have found is that with debug enabled the . before the file extension is being replaced with an underscore.

url created with debug enabled:
`http://localhost/OE/_cassette/file/Content/images/top_9db8d19b539a59b45ea081c8bf92e7e8a949c4d3_jpg`

url created with debug disabled (working):
`http://localhost/OE/_cassette/file/Content/images/top_9db8d19b539a59b45ea081c8bf92e7e8a949c4d3.jpg`

Our configuration:

``` c#
public class CassetteConfiguration : ICassetteConfiguration
{
    public void Configure(BundleCollection bundles, CassetteSettings settings)
    {
        // Configure your bundles here...
        // Please read http://getcassette.net/documentation/configuration
        bundles.Add<StylesheetBundle>("Content/css", bundle => bundle.PageLocation = "site");
        bundles.Add<StylesheetBundle>("Content/themes/base", bundle => bundle.PageLocation = "jquery.ui");

        bundles.Add<ScriptBundle>("Scripts");
        bundles.Add<ScriptBundle>("Content/js");
        bundles.AddPerIndividualFile<ScriptBundle>("Content/js/per-page", 
                    customizeBundle: bundle => bundle.PageLocation = "BodyLast");
    }
}
```

**Comment by andrewdavey** [comment]
I can't reproduce this (running on current `master` branch).

I'm wondering if the CSS file is loading from browser cache? The cache breaking querystring is the hash of the original file (which has not actually changed). However the change in the way Cassette builds the URL (`"."` instead of `"_"`) has resulted in a broken link. Try clearing your cache and see if that fixes things.

Otherwise can you also try pulling down `master` to see if that works for you?

I'm starting to think the asset querystring cache breaker should be the hash of the _output_ not the _input_ file... The Bundle hash works this way now.

**Comment by SLaks** [comment]
This is the result of a breaking change in the URL generation.

Cassette recently switched the `_` to `.`, so the old `_`-based URLs now 404.

However, the CSS hashes didn't change, so once you have the old `_`-based CSS files in your browser cache, the server will keep sending 304 Not Modified even though they actually have changed.

It's working in Release mode because you didn't have `_`-based Release-mode (minified) files in your cache.

The simple fix is to change RawFileRouteHandler to accept `.` or `_` (change `\.` to `[._]` in the regex).

A better fix would be to hash the processed files instead of the raw source; this would allow for other future changes too.

As a temporary fix, press Ctrl+F5 to force skip the cache.

**Comment by andrewdavey** [comment]
The latest in `master` now hashes the asset output instead of the original file.
