### ISSUE TITLE
 @Assets.Scripts.Render(); is Generating Guid at random Interval

### ISSUE THREAD

**Issue by AvinashTiwari** [andrewdavey/cassette#217]
Hi,

i am using cassette ..

at _layout page Some time " @Assets.Scripts.Render();" only Generates  Guid  and doesn't render java script tag..

can anybody please let me know the reason behind

**Comment by tomdenny** [comment]
While I could be wrong, I _thought_ `@Assets.Scripts.Render()` was deprecated a while ago in favor of `@Bundles.RenderScripts()`  Any chance you're using a fairly old version of Cassette?  There's some very good reasons to upgrade if you are.  Including a security fix.

**Comment by kevcenteno** [comment]
This is happening for me as well for 1.2.0 in a webforms project.  We can recreate the bug 100% of the time whenever we throw a 404 exception.

**Comment by tomdenny** [comment]
Hi Chigro, is there any more information you can give on this?  Perhaps what you're using to render the scripts (`@Bundles.RenderScripts()`) and what the output looks like (`<script src="4fe4a62b41800822782c458e6b12c9ce7fed557a" type="text/javascript"></script>`?)  

I have a faint memory that I've seen this behavior before when I first started using Cassette but I haven't seen it in a long time and I suspect I was just doing something strange.

**Comment by tomdenny** [comment]
I'm not sure I follow the 404 status code either.  You're using cassette to output some scripts on a 404 error page?

**Comment by kevcenteno** [comment]
Since I'm using webforms, not MVC, to render scripts I'm using
    `<%= Bundles.RenderStylesheets() %>`
and the output looks like this
    `58ab2d68-1463-47e3-857d-7b8a51122cc2 d4bb04e1-20f1-4c67-be5d-597d73693b8a`
No script tags, no link tags, just the string sitting there by itself in the head.  Real strange. 

CSS and JS files are being declared in the CassetteConfiguration.cs file.  

So here's the thing... It works perfect for _all_ pages, EXCEPT in the following case/example:

To fetch a blog post, we pass in an ID as a parameter:  http://www.example.com/blog.aspx?=1234
Now, in our code, if an ID isn't in our DB, instead of throwing a 505 error, we throw a 404 error (which is configured in our web.config file to point to a custom 404.aspx page).  _This_ is when we see the GUID.

It may be related to this bug: https://github.com/andrewdavey/cassette/issues/233

**Comment by kevcenteno** [comment]
I got around this by adding the following to my web.config
    `<system.webServer>
        ...
        <httpErrors existingResponse="Replace" errorMode="Custom">
                <remove statusCode="404" subStatusCode="-1" />
                <error statusCode="404" prefixLanguageFilePath="" path="/404.aspx" responseMode="ExecuteURL" />
        </httpErrors>
        ...
    </system.webServer>`

The key here is existingResponse="Replace"

**Comment by AvinashTiwari** [comment]
dll  which we are using is of version "0.8.1.0 "

**Comment by kevcenteno** [comment]
Avinash, how do you recreate the error?

**Comment by colinasquith** [comment]
This also happens for me using v1.2 or v2 (beta) - I just get a GUID written into the source code of the web page. Sometimes the pages work, sometimes they don', the same page can work then later it doesn't. This is in release mode for me (debug off).

**Comment by colinasquith** [comment]
I should add that this seems to be an issue for one site I work with, but not another. They use the same version and setup. The site that fails has a lot more pages, not sure if that is related.

**Comment by ericbock** [comment]
I'm running into this same issue with Cassette 2 beta 3. In my case it happens when I use it in conjunction with [DevTrends MVCDonutCaching](http://mvcdonutcaching.codeplex.com/). Any view returned by an MVC action method that has a `[DonutOutputCache]` attribute on it will display properly when it is "live" (hitting the action method) but will fail (displaying guids in place of scripts or css) whenever I get a cached version.

**Comment by ericbock** [comment]
It turns out that setting `rewriteHtml=false` in my web.config ([Cassette Configuration](http://getcassette.net/documentation/configuration)) resolves this issue with DevTrends MVCDonutCaching.

**Comment by jpleclerc** [comment]
I have the same problem. When rewriteHtml=true, renderScripts() generated a GUID. The problem here is that I need the rewriteHtml because I use masterpages.

**Comment by Ridermansb** [comment]
@L1ghtm4n found a solution to your problem?
I'm having the same problem!

**Comment by andrewdavey** [comment]
Have you tried using `Cassette 2.1.0-beta4` this has an updated HTML output rewriter which may fix things:

```
Update-Package Cassette -Pre
```

**Comment by jclementson** [comment]
A hint in case it helps anyone: I found this still happening in version 2.4.2 (as well as Cassette sometimes giving up half-way through a bundle and only outputting some of the assigned scripts), however I could resolve all these issues by ensuring that any partial view that adds script references is not being cached in the whole page. If the partial view is cached, Cassette works as expected on first page load in a new thread, but subsequent page loads are broken.
