### ISSUE TITLE
cassette don't work for Classic AppPool when debug="true" 

### ISSUE THREAD

**Issue by jalex** [andrewdavey/cassette#218]
Enviroment: IIS 7.5, WebForms, .NET 4 Framework, "ASP.NET v4.0 Classic" Application Pool

Cassette configuration:
    <i>bundles.Add<ScriptBundle>("jquery", "Scripts/jquery-1.7.1-vsdoc.js");</i>

In master page:
     <i><%
         Bundles.Reference("jquery");
      %></i>

When config file contains <i>&lt;compilation debug="false"&gt;</i> that work fine.

When config file contains <i>&lt;compilation debug="true"&gt;</i> that I have error
"GET http://localhost/rtw/_cassette/asset/ass/jquery/jquery-1.7.1-vsdoc.js?6ee2d75b5f619a79d126eb01023ef3ae76e5a7d4 404 Not Found" </i>

When I change the Application Pool from "ASP.NET v4.0 Classic" to "ASP.NET v4.0" - that all work fine.

**Comment by LodewijkSioen** [comment]
Hi,

we're having the same problem. My theory is that this is caused by the presence of a dot ('.') in the URL when the files are not bundled. This cases IIS to trigger the StaticFileHandler and the request never ends up in the asp.net pipeline. When debug is set to false, the url contains no dot. The request is sent to asp.net and routing picks it up.

My suggestion would be to remove the dots from the url when the files are served unbundled. Or to put the path to the file in a querystring parameter.

Cheers,
Lodewijk

**Comment by andrewdavey** [comment]
Cassette v2 fixes this by using `cassette.axd` handler so that the rest of the URL is moved into the PathInfo and ignored by IIS.

**Comment by LodewijkSioen** [comment]
It does so indeed. We've switched to v2 and everything works.
