### ISSUE TITLE
Cassette not recognising absolute paths reference path's

### ISSUE THREAD

**Issue by nazjunaid** [andrewdavey/cassette#24]
Most of our JavaScript references are absolute paths which Cassette seems to treat as relative paths.

Eg.

```
/// <reference path="/resources/scripts/shared/utils.js"/>
/// <reference path="/resources/scripts/shared/location.js"/>
/// <reference path="/resources/scripts/shared/sector.js"/>
/// <reference path="/resources/scripts/shared/account.js"/>
```

We get errors like 

The file "resources/scripts/account/edit//resources/scripts/shared/utils.js" is referenced by "resources/scripts/account/edit/contact.js" but cannot be found.

I think it should support absolute paths in reference paths

**Comment by andrewdavey** [comment]
That sounds like a reasonable enhancement to make. I wonder if using a '~/' prefix makes more sense, since it's really absolute to the web application, not the system.

Do those relative paths still make the Visual Studio intellisense work? Does it know to treat the leading "/" as "from the web application root directory"?

**Comment by andrewdavey** [comment]
(I updated your issue to use triple back ticks around the code block, so the angle brackets work.)

**Comment by nazjunaid** [comment]
Visual studio and resharper 6 intellisense works with absolute paths

Thanks for fixing the post :)

**Comment by andrewdavey** [comment]
Cassette 0.6 allows paths to start with "/" and "~/". It treats them both as application directory relative.
