### ISSUE TITLE
Make more types public for plug-in consumption

### ISSUE THREAD

**Issue by onionhammer** [andrewdavey/cassette#317]
[assembly: InternalsVisibleTo("Cassette.CoffeeScript")]
[assembly: InternalsVisibleTo("Cassette.Less")]
[assembly: InternalsVisibleTo("Cassette.Sass")]

You're giving your own plugins first class treatment by letting them access to (arbitrarily?) internal classes?

**Comment by andrewdavey** [comment]
In v1 there were no plugins and everything was included in the one Cassette assembly. At the time I was trying to avoid public API churn, and conform to http://semver.org/ . That's why lots of stuff is internal at the moment.

Using `InternalsVisibleTo` was a stop gap measure to move to plug-in model in v2. I still don't love the idea of making all things public. However, it would be great to now expose more extension points.

**Comment by onionhammer** [comment]
Understandable; but look here to see through the frustration I'm going through;
http://pastebin.com/7as4xEEZ

I'm trying to get TypeScript compiled JS files to be included into the script bundle, this works as expected but the <reference> comments are pointing to .ts files instead of .js files, so I'm attempting to correct them.. but you have several read-only properties and internal classes and methods which make this very difficult, so I am forced to use reflection.

Note that I may not be doing this the 'correct' way, but I really can't find any documentation on what I'm doing.

**Comment by andrewdavey** [comment]
Can you create a pull request that makes the types and members you need access to public?

**Comment by onionhammer** [comment]
Sure, but it'll have to wait til this weekend.

Thanks for your attention :)
