### ISSUE TITLE
Error 330 (net::ERR_CONTENT_DECODING_FAILED): Unknown error.

### ISSUE THREAD

**Issue by tommck** [andrewdavey/cassette#33]
I get this error if I have the following line in the <system.webServer> section in my web.config (IIS7)

```
<urlCompression doDynamicCompression="true" dynamicCompressionBeforeCache="true" />
```

Without this, everything seems OK, otherwise, I can't even load a single page..

**Comment by andrewdavey** [comment]
Thanks for reporting the problem. That sounds like the GZip encoding is going wrong somewhere. I'll have to look into it.

**Comment by andrewdavey** [comment]
I think this is the same problem http://stackoverflow.com/questions/4313162/urlcompression-response-filter-conflict

The page HTML, which Cassette does some rewriting to, is getting compressed _before_ the Cassette response filter runs. Options:
1. Set `dynamicCompressionBeforeCache="false"`. Not ideal, since I assume you have good reason for using that :)
2. Cassette could detect pre-compressed page and not attempt to rewrite. You'd lose the ability of referencing asset modules in partial views which are actually rendered further up the page.
3. Cassette could decompress the page HTML before rewriting. This may be tricky, given the response filter only gets chunks of output to process at a time. Research required...

**Comment by andrewdavey** [comment]
Latest code in master should fix this. It performs `response.Flush()` in `PostRequestHandlerExecute`. This means the page rewriting filter is called before the page output is compressed for the output cache.

Can you please test and let me know if it's working for you now? 
Thanks.

**Comment by andrewdavey** [comment]
I had to remove the Flush call. It breaks too many other things in ASP.NET.

For now there are two options.
1. Set `dynamicCompressionBeforeCache="false"`
2. In the Cassette configuration class, set `application.HtmlRewritingEnabled = false;` This means that asset `Reference` calls in a page must occur before the call to `Render`. Only partial views that want to put references into the `<head>` are affected by this, since they are executed after the head has been rendered.

**Comment by tommck** [comment]
Unfortunately, I had to leave off implementing Cassette for now (stability
of code base).  I will be reattempting soon and then will be able to try and
help figure things out.

Thanks for the work,

Tom

**Comment by andrewdavey** [comment]
Yes, the code has been pretty changeable while under development - the perils of release early, release often!

I'm hoping to get everything settled and ready for 1.0 soon. So please keep an eye on the project. When you do give it another go, give me a shout if you run into any issues.
