### ISSUE TITLE
Cassette breaks Composite C1 CMS admin console

### ISSUE THREAD

**Issue by madsgodvinjensen** [andrewdavey/cassette#412]
I'm using the Cassette.AspNet package with a Composite C1 web site. It seems that the CassetteHttpModule is breaking the CMS admin console - if I remove the module from web.config everything, except Cassette, works fine. I'm not sure what goes wrong, it could be a million things.

As a solution I'm thinking adding a configuration feature to Cassette to not run the module for requests with the configured paths. I can implement it myself and do a pull request if it helps.

**Comment by ThomasSchmidt** [comment]
Have you tried setting rewriteHtml="false" in web.config in the cassette section?

**Comment by madsgodvinjensen** [comment]
Well that worked beautifully. But I have no idea why - can you explain?

**Comment by burningice2866** [comment]
Seems like no one else is answering, but the reason setting rewriteHtml to false works is because its prevents the PlaceholderReplacingResponseFilter (https://github.com/andrewdavey/cassette/blob/master/src/Cassette.Aspnet/PlaceholderReplacingResponseFilter.cs) to be attached for the request. I'm sure it does all kinds of awesome processing, but it for sure also breaks the functionality of the C1 Console - and assumingly also other javascript-heavy applications.
