### ISSUE TITLE
How to use CDN with "fallback" local script?

### ISSUE THREAD

**Issue by sfmskywalker** [andrewdavey/cassette#8]
I assume one would use "Assets.Scripts.ExternalReference" to include a script from a CDN, but in case that resource is unavailable, one would write the following script:

<script type="text/javascript">  !window.jQuery && document.write(unescape('%3Cscript src="@Url.Content("~/Scripts/libs/jquery-1.6.2.min.js")"%3E%3C/script%3E'))</script> 

It's possible to put this script inside another .js file, but maybe it's an idea to add an overload to ExternalReference that will take both an external url (CDN) and a local url (fallback).

Ps. sorry if this isn't the right place to post suggestions!

**Comment by andrewdavey** [comment]
Thanks for the suggestion; this is absolutely the right place. Keep them coming! :)

The fallback script would need to be separated from the main application scripts, to avoid it getting added to a module and then included twice in the page. So having a "fallback-scripts" folder, for example, would make this feature is feasible.

I need to give the external script feature some attention in general. Since I think they should really be configured in web.config and then a page just says "I want jQuery please". Something like this perhaps:

``` xml
<cassette>
  <scripts>
    <add path="jquery" cdn="//ajax.googleapis.com/ajax/libs/jquery/1.6.1/jquery.min.js" fallback="fallback-scripts/jquery.js" />
  </scripts>
</cassette>
```

in page:

```
Assets.Scripts.Reference("jquery");
```

**Comment by sfmskywalker** [comment]
I would definitiely love that!
Although this also means that each CDN url will become a module on its own, which means one subfolder per CDN url which will only contain a single (fallback) file (unless I'm not seeing it correctly).

On the other hand, I would probably be using just jQuery. Never used another CDN url before :)
Even if I had 4 CDN urls, it wouldn't be bad to have a subfolders for each of them.

**Comment by andrewdavey** [comment]
The fallback scripts would not be built into modules. They'll exist just in a one separate folder of scripts.

Technically each external (CDN) URL is treated as a module by Cassette already. It's just that the URL is pre-set, instead of Cassette using it's own HTTP handler URL.

**Comment by andrewdavey** [comment]
http://getcassette.net/documentation/scripts/external-modules
